### ISSUE TITLE
css fixes

### ISSUE THREAD

**Issue by Suhmedoh** [kmanc/Riot_Challenge_2016#10]
Fix gap at bottom of results page, fix link hover effects, fix link placement on results page, make things look better in general

**Comment by kmanc** [comment]
lol can you apply that last one to me as well? does css do that?

**Comment by kmanc** [comment]
Title case complete, a few spacing things complete, not sure what link placement is referring to, would be cool to have responsive sizing. Other than that things looking pretty good!

**Comment by kmanc** [comment]
On the results page I added a second button to recalculate a team based on picks/bans, but I can't get the two buttons (Home and Recalculate) to spread apart. Maybe I don't understand CSS the way I think I do lol. @Suhmedoh leaving them unspaced for now while I implement the other shit but if you could take a look on the feature branch I'd appreciate it :)
