### ISSUE TITLE
Front page design (for when you're bored...super low priority)

### ISSUE THREAD

**Issue by kmanc** [kmanc/Riot_Challenge_2016#7]
I think we can probably format the landing page a little better, and make it look prettier.  For instance, I don't know if we need to have instructions explaining that they should choose their region, and how many champions to check (they can fool around with that and see what they like)

Could we also put the region dropdown above (or below) the champion number?  I think it might look a little nicer.  And I think we can take out the example summoners.

Hopefully in the future we can remove the part that says the need to have played ranked...but that is more on me/Riot because until we get normal game data, we're out of luck.

**Comment by kmanc** [comment]
@Suhmedoh I don't know if this was intended or not, but I think originally you had made the div with the summoner/champ info stretched vertically the whole size of the page, so that you could just move the mouse to the region of the screen to change the splash art you see.  Now you need to physically hover over the bar at the bottom.  I think either way is fine, but just wanted to point that out in case you had made that change by accident.

Also (this could be some funkiness on my Mac's screen) you can scroll down the page a little bit.  Not really sure why because nothing is below what we display.  I'll try to remember to see if it happens on my desktop when I hit VA

**Comment by Suhmedoh** [comment]
Definitely scared something up that made the page able to scroll, probably a padding out margin issue; and I can clean up the landing page too, no problem
