### ISSUE TITLE
I don't like PHP

### ISSUE THREAD

**Issue by kmanc** [kmanc/Riot_Challenge_2016#8]
There are a bunch of reasons we should consider moving to a new stack, but I think the first of which is that PHP is gross :P 

Also I noticed that whatever input sanitization we are using is not allowing for special characters in summoner names (and the internet says they pretty much suck at what they do lol)

**Comment by Suhmedoh** [comment]
Fair enough, I would also like to move to a different stack, perhaps something like react, vuejs, or angular since I'm already familiar enough with JS, I'll see if I can find time to do a rewrite of the front end

**Comment by kmanc** [comment]
Cool! I was also looking into Flask (Python). Got scared the other day when a coworker started fuzzing summonsquad to see how much he could get away with by putting in funky arguments. It was more than I wanted to see :P

**Comment by kmanc** [comment]
@Suhmedoh Flask is basically done (flask branch), only two things left to do...

- style the pages (I've passed all the info needed to the error and results pages but its gross)
- deploy the app on our instance (pretty sure that isn't too bad)

**Comment by kmanc** [comment]
BOOM
