### ISSUE TITLE
Team creation based on constraints

### ISSUE THREAD

**Issue by kmanc** [kmanc/Riot_Challenge_2016#9]
Revisit of "these champs have been picked and these champs have been banned" recalculation of teams

**Comment by kmanc** [comment]
Probably gonna see what I can come up with over the next few weeks

**Comment by Suhmedoh** [comment]
Could allow user to pick likely bans/ undesired champs before we generate team, and/or give the option to say "summoner 3 is only gonna play Lee sin top, so pick the best team to support him"

**Comment by kmanc** [comment]
Yea @Suhmedoh the only thing about that is that it "somewhat" defeats the purpose of the app. I see the argument for saying "Sum1 is only gonna do this so please help" but what would be better is if Sum1 doesn't do that :P
